### ISSUE TITLE
MQTT 2.0 has broken docker compose

### ISSUE THREAD

**Issue by bryanmcgrane** [brocaar/chirpstack-docker#44]
I tried to deploy the docker-compose configuration, and ran into an issue where MQTT was refusing to connection from all servers. Due the the below breaking change:

https://github.com/eclipse/mosquitto/issues/2040

I was able fix this by fixing the MQTT docker container to 1.6 via:

```
 mosquitto:
    image: eclipse-mosquitto:1.6
    ports:
      - 1883:1883

```
